### ISSUE TITLE
Cannot bind ports below 1000

### ISSUE THREAD

**Issue by tamara-schmitz** [t4skforce/syncthing-relay#1]
I'd like to run my relay on port 80 or 993 but my Docker container logs display the following error message: `2017/11/20 16:23:34 listener.go:29: listen tcp 0.0.0.0:993: bind: permission denied`

There are various approaches to fixing this:
- run the relay executable as root
- the approach described in the documentation implemented for whenever you use the SERVER_PORT environment variable: https://docs.syncthing.net/users/strelaysrv.html#running-on-port-443-as-an-unprivileged-user
- just expose the _ext-address_ option as an environment variable and change the documentation accordingly.

**Comment by t4skforce** [comment]
Can you please try again with the added option "RELAY_OPTS".

**Comment by tamara-schmitz** [comment]
Works as intended thanks.
