### ISSUE TITLE
CA certificates not included

### ISSUE THREAD

**Issue by tamara-schmitz** [t4skforce/syncthing-relay#3]
I'd like to advertise my relay in in a relay pool, however CA certificates are required in order to connect to the directory via TLS.
Error message: `Error joining pool https://relays.syncthing.net/endpoint Post https://relays.syncthing.net/endpoint: x509: failed to load system roots and no roots provided`

I temporarely fixed this by linking a different ca-certificates.crt file 

This can be fixed by installing the Debian package `ca-certificates`.

**Comment by t4skforce** [comment]
Strange this should already be the case as per 
`ENV REQUIREMENTS ca-certificates`
which is not uninstalled in build cleanup. I have to the if maybe `apt-get --auto-remove` purges the package

**Comment by t4skforce** [comment]
yep confirmed... 
```
The following packages will be REMOVED:

  ca-certificates* curl* libcurl3* libffi6* libgmp10* libgnutls30*
  libgssapi-krb5-2* libhogweed4* libidn11* libidn2-0* libk5crypto3*
  libkeyutils1* libkrb5-3* libkrb5support0* libldap-2.4-2* libldap-common*
  libnettle6* libnghttp2-14* libp11-kit0* libpsl5* librtmp1* libsasl2-2*
  libsasl2-modules-db* libssh2-1* libssl1.0.2* libssl1.1* libtasn1-6*
  libunistring0* openssl*
```

**Comment by t4skforce** [comment]
fixed, `ca-certificates` included in container now
